require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe KolegijisController do

  # This should return the minimal set of attributes required to create a valid
  # Kolegiji. As you add validations to Kolegiji, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KolegijisController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all kolegijis as @kolegijis" do
      kolegiji = Kolegiji.create! valid_attributes
      get :index, {}, valid_session
      assigns(:kolegijis).should eq([kolegiji])
    end
  end

  describe "GET show" do
    it "assigns the requested kolegiji as @kolegiji" do
      kolegiji = Kolegiji.create! valid_attributes
      get :show, {:id => kolegiji.to_param}, valid_session
      assigns(:kolegiji).should eq(kolegiji)
    end
  end

  describe "GET new" do
    it "assigns a new kolegiji as @kolegiji" do
      get :new, {}, valid_session
      assigns(:kolegiji).should be_a_new(Kolegiji)
    end
  end

  describe "GET edit" do
    it "assigns the requested kolegiji as @kolegiji" do
      kolegiji = Kolegiji.create! valid_attributes
      get :edit, {:id => kolegiji.to_param}, valid_session
      assigns(:kolegiji).should eq(kolegiji)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Kolegiji" do
        expect {
          post :create, {:kolegiji => valid_attributes}, valid_session
        }.to change(Kolegiji, :count).by(1)
      end

      it "assigns a newly created kolegiji as @kolegiji" do
        post :create, {:kolegiji => valid_attributes}, valid_session
        assigns(:kolegiji).should be_a(Kolegiji)
        assigns(:kolegiji).should be_persisted
      end

      it "redirects to the created kolegiji" do
        post :create, {:kolegiji => valid_attributes}, valid_session
        response.should redirect_to(Kolegiji.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved kolegiji as @kolegiji" do
        # Trigger the behavior that occurs when invalid params are submitted
        Kolegiji.any_instance.stub(:save).and_return(false)
        post :create, {:kolegiji => {}}, valid_session
        assigns(:kolegiji).should be_a_new(Kolegiji)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Kolegiji.any_instance.stub(:save).and_return(false)
        post :create, {:kolegiji => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested kolegiji" do
        kolegiji = Kolegiji.create! valid_attributes
        # Assuming there are no other kolegijis in the database, this
        # specifies that the Kolegiji created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Kolegiji.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => kolegiji.to_param, :kolegiji => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested kolegiji as @kolegiji" do
        kolegiji = Kolegiji.create! valid_attributes
        put :update, {:id => kolegiji.to_param, :kolegiji => valid_attributes}, valid_session
        assigns(:kolegiji).should eq(kolegiji)
      end

      it "redirects to the kolegiji" do
        kolegiji = Kolegiji.create! valid_attributes
        put :update, {:id => kolegiji.to_param, :kolegiji => valid_attributes}, valid_session
        response.should redirect_to(kolegiji)
      end
    end

    describe "with invalid params" do
      it "assigns the kolegiji as @kolegiji" do
        kolegiji = Kolegiji.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Kolegiji.any_instance.stub(:save).and_return(false)
        put :update, {:id => kolegiji.to_param, :kolegiji => {}}, valid_session
        assigns(:kolegiji).should eq(kolegiji)
      end

      it "re-renders the 'edit' template" do
        kolegiji = Kolegiji.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Kolegiji.any_instance.stub(:save).and_return(false)
        put :update, {:id => kolegiji.to_param, :kolegiji => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested kolegiji" do
      kolegiji = Kolegiji.create! valid_attributes
      expect {
        delete :destroy, {:id => kolegiji.to_param}, valid_session
      }.to change(Kolegiji, :count).by(-1)
    end

    it "redirects to the kolegijis list" do
      kolegiji = Kolegiji.create! valid_attributes
      delete :destroy, {:id => kolegiji.to_param}, valid_session
      response.should redirect_to(kolegijis_url)
    end
  end

end
